mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    #host localhost
    host: 10.0.2.15
    port: 1883
    keepalive: 60
  private_path: device/001
#serializer: msgpack:dumps
#deserializer: msgpack:loads
serializer: json:dumps
deserializer: json:loads
bridge:
  # diode_node_commands
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /diode_node_commands
    topic_to: diode_node_commands
#rostopic pub /testTopic -> MQTT på topic "testTopic"
#MQTT client.publish("echo", "{"data":"string"}" (skal kobles sammen med '"')
#kommer ind i ROS på rostopic /back
